import { Asset } from 'contentful'
import { DeepReplace } from '@/types/util'
import {
  type IWork,
  type IWorkFields,
  type IClient,
  type IClientFields,
  type ITech,
  type ITechFields,
  type IImpact,
  type IImpactFields,
  type IAuthor,
  type IAuthorFields,
  type IIntroSection,
  type IIntroSectionFields,
  type IWorkSection,
  type IWorkSectionFields,
} from './types.generated'

// Fix autogenerated contentful types

export type TAsset = {
  url: string
}

export type TEmoji = {
  __typename: string
  sys: {
    id: string
  }
  emojiImage: {
    sys: {
      id: string
    }
    title: string
    url: string
    width: number
    height: number
  }
}

export type TImageList = {
  __typename: string
  sys: {
    id: string
  }
  images: {
    items: {
      sys: {
        id: string
      }
      title: string
      url: string
      width: number
      height: number
    }[]
  }
}

export type TDocument = {
  json: Document
  links: {
    entries: {
      block: TImageList[]
      inline: TEmoji[]
    }
  }
}

export type TClient = DeepReplace<IClient & IClientFields, Asset, TAsset>
export type TTech = DeepReplace<ITech & ITechFields, Asset, TAsset>
export type TImpact = DeepReplace<IImpact & IImpactFields, Asset, TAsset>
export type TAuthor = DeepReplace<IAuthor & IAuthorFields, Asset, TAsset>
export type TWorkItem = DeepReplace<
  IWork & Omit<IWorkFields, 'body'>,
  Asset,
  TAsset
> & {
  client: TClient
  techs: TTech[]
  impacts: TImpact[]
  body: TDocument
}

export type TIntroSection = IIntroSection &
  IIntroSectionFields & { author: TAuthor }

export type TWorkSection = Omit<
  IWorkSection & IWorkSectionFields,
  'workItems'
> & {
  workItems: TWorkItem[]
}
