// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.
import { Document } from '@contentful/rich-text-types'
import { Asset, Entry } from 'contentful'

export interface IAuthorFields {
  /** Name */
  name: string

  /** Bio */
  bio: string

  /** Photo */
  photo: Asset
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'author'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IClientFields {
  /** Name */
  name: string

  /** Logo Map */
  logoMap: Asset
}

export interface IClient extends Entry<IClientFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'client'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IEmojiFields {
  /** Name */
  name: string

  /** Emoji Image */
  emojiImage: Asset
}

export interface IEmoji extends Entry<IEmojiFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'emoji'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImageListFields {
  /** Name */
  name: string

  /** Images */
  images?: Asset[] | undefined
}

export interface IImageList extends Entry<IImageListFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'imageList'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImpactFields {
  /** Body */
  body: string
}

export interface IImpact extends Entry<IImpactFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'impact'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IIntroSectionFields {
  /** Title */
  title: string

  /** Body */
  body: string

  /** Author */
  author: IAuthor

  /** Brands Title */
  brandsTitle: string

  /** Brands */
  brands?: Asset[] | undefined
}

export interface IIntroSection extends Entry<IIntroSectionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'introSection'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ISocialMediaLinkFields {
  /** Name */
  name: string

  /** Icon */
  icon: Asset

  /** href */
  href: string
}

export interface ISocialMediaLink extends Entry<ISocialMediaLinkFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'socialMediaLink'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITechFields {
  /** Name */
  name: string

  /** Icon */
  icon: Asset
}

export interface ITech extends Entry<ITechFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'tech'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IWorkFields {
  /** Title */
  title: string

  /** Alt Title */
  altTitle?: string | undefined

  /** Start Date */
  startDate?: string | undefined

  /** End Date */
  endDate?: string | undefined

  /** Client */
  client: IClient

  /** Body */
  body: Document

  /** Card Video */
  cardVideo: Asset

  /** Card Back Text */
  cardBackText?: string | undefined

  /** Techs */
  techs?: ITech[] | undefined

  /** Impacts */
  impacts?: IImpact[] | undefined
}

export interface IWork extends Entry<IWorkFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'work'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IWorkSectionFields {
  /** Title */
  title: string

  /** Body */
  body?: string | undefined

  /** Work Items */
  workItems: IWork[]
}

export interface IWorkSection extends Entry<IWorkSectionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'workSection'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'author'
  | 'client'
  | 'emoji'
  | 'imageList'
  | 'impact'
  | 'introSection'
  | 'socialMediaLink'
  | 'tech'
  | 'work'
  | 'workSection'

export type IEntry =
  | IAuthor
  | IClient
  | IEmoji
  | IImageList
  | IImpact
  | IIntroSection
  | ISocialMediaLink
  | ITech
  | IWork
  | IWorkSection

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
